### ISSUE TITLE
Bug al presionar boton punto de pedido/order point en el producto

### ISSUE THREAD

**Issue by mschettini** [AntaresConsulting/odoo-marble#1]
Explota la app en la vista de producto cuando se presiona el boton punto de pedido/order point
Client Traceback (most recent call last):
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/addons/web/controllers/main.py", line 1128, in call_kw
    return self._call_kw(req, model, method, args, kwargs)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/maximo/openerp/clientes/anton/V7/product_marble/models/product_product.py", line 319, in name_get
    attrs = self._get_attrs(cr, uid, ids, context=context)
  File "/home/maximo/openerp/clientes/anton/V7/product_marble/models/product_product.py", line 289, in _get_attrs
    for p in self.browse(cr, uid, ids, context=context):
  File "/home/maximo/openerp/openerp7/openerp-7.0-20140406-230547/openerp/osv/orm.py", line 505, in __iter__
    raise NotImplementedError("Iteration is not allowed on %s" % self)
NotImplementedError: Iteration is not allowed on browse_record(product.product, 9)

**Comment by jacksolutions** [comment]
getting this error on odoov8.

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/product_marble/models/partner.py", line 79, in create
    if data['has_local_stock']:
ParseError: "has_local_stock" while parsing /opt/odoo/custom/addons/product_marble/data/users_data.xml:21, near
<record id="anton_david" model="res.partner">
            <field name="name">David Antokolec</field>
            <field name="company_id" ref="base.main_company"/>
            <field name="email">david@marmolesanton.com.ar</field>
            <field name="customer" eval="False"/>
            <field name="supplier" eval="False"/>
            <field name="lang">es_AR</field>
        </record>

**Comment by jacksolutions** [comment]
```
if data['has_local_stock']:
```

ParseError: "has_local_stock" while parsing /opt/odoo/custom/addons/product_marble/data/users_data.xml:21, near
<record id="anton_david" model="res.partner">
            <field name="name">David Antokolec</field>
            <field name="company_id" ref="base.main_company"/>
            <field name="email">david@marmolesanton.com.ar</field>
            <field name="customer" eval="False"/>
            <field name="supplier" eval="False"/>
            <field name="lang">es_AR</field>
        </record>

**Comment by jacksolutions** [comment]
any update on it ?

**Comment by arosenbrock** [comment]
Hello Jack,
I could not even see this incident, in these days I'll be watching.
Greeting.-

_______________________________________________________________________
Ariel Rosenbrock - Lic. en Sistemas de Información - (11-15) 6189-3682
Capital Federal - Buenos Aires - Argentina

**Comment by jacksolutions** [comment]
thank you @arosenbrock for your response on this issue.. yes this issue happens on odoo v8! i tried to solve it but in vain.. if you could solve this error and update the repo, that would be appreciable.

many thanks

**Comment by arosenbrock** [comment]
it was resolved.
greeting.-

_______________________________________________________________________
Ariel Rosenbrock - Lic. en Sistemas de Información - (11-15) 6189-3682
Capital Federal - Buenos Aires - Argentina
