### ISSUE TITLE
Wrong value for res.partner.lang: 'es_AR'

### ISSUE THREAD

**Issue by jacksolutions** [AntaresConsulting/odoo-marble#2]
now i am getting below error on fresh install on odoo v8.. 

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/product_marble/models/partner.py", line 82, in create
    return super(res_partner, self).create(cr, uid, data, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/res/res_partner.py", line 573, in create
    partner = super(res_partner, self).create(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4040, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4160, in _create
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 2255, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/opt/odoo/odoo-server/openerp/fields.py", line 1324, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ParseError: "Wrong value for res.partner.lang: 'es_AR'" while parsing /opt/odoo/custom/addons/product_marble/data/users_data.xml:21, near
<record id="anton_david" model="res.partner">
            <field name="name">David Antokolec</field>
            <field name="company_id" ref="base.main_company"/>
            <field name="email">david@marmolesanton.com.ar</field>
            <field name="customer" eval="False"/>
            <field name="supplier" eval="False"/>
            <field name="lang">es_AR</field>
        </record>

**Comment by jacksolutions** [comment]
removing this line from user_data.xml "<field name="lang">es_AR</field>" solves the issue

**Comment by jacksolutions** [comment]
okay i have installed this module but i dont see any use of this module? i see some new menus created but it opens the same page everytime for example "works" menu it opens exactly same as customers page.

same in options in products section... what am i doing wrong? this module solves which purpose? any documentation or use case of this module? that will help!

**Comment by arosenbrock** [comment]
Hi Jack,

Partner (customer and suppliers) and Works "menus" are similar, with the
difference that in "Works" menu, it filter the "Partners" with "Works"
properties (flag) in True.

This "Marble" module is oriented to "Marble Works" for a Cliente our.

In "Partner" menu, a "Customer" can is a "Company", a "Company" can have
many "Works". For it we place a "Works tab" in "Partner".

(Cutomer = True) and (Company = True) and (is_work = True [this Partner
isn't "Work"]) so enabled tab "Works".

In "Works" tab, can register many "Works"...

About documentation for this, we don't have.

_______________________________________________________________________
Ariel Rosenbrock - Lic. en Sistemas de Información - (11-15) 6189-3682
Capital Federal - Buenos Aires - Argentina
